export const movie = [
    {
        name: "Black Swan",
        poster: "https://upload.wikimedia.org/wikipedia/en/6/68/Black_Swan_poster.jpg",
        rating: 8.0,
        summary: "A psychological thriller that follows the intense rivalry between two ballet dancers competing for the lead role in a production of 'Swan Lake', blurring the lines between reality and hallucination.",
        glimpse: 'https://www.youtube.com/watch?v=5jaI1XOB-bs',
        director: "Darren Aronofsky",
        year: 2010,
        cast: ["Natalie Portman", "Mila Kunis"],
        genre: "Thriller",
        id: 1
    },
    {
        name: "Before Sunrise",
        poster: "https://upload.wikimedia.org/wikipedia/en/d/da/Before_Sunrise_poster.jpg",
        rating: 8.1,
        summary: "A romantic drama that unfolds over the course of a single night in Vienna, as two strangers, an American man and a French woman, explore the city and share intimate conversations.",
        glimpse: 'https://youtu.be/6MUcuqbGTxc?si=ws6reRq5We17Smdi',
        trailer:"https://www.youtube.com/embed/6MUcuqbGTxc?si=ShGVvw3vMVBojbmz",
        director: "Richard Linklater",
        year: 1995,
        cast: ["Ethan Hawke", "Julie Delpy"],
        genre: "Romance",
        id: 2
    },
    {
        name: "Whiplash",
        poster: "https://upload.wikimedia.org/wikipedia/en/0/01/Whiplash_poster.jpg",
        rating: 8.5,
        summary: "A gripping drama about the intense relationship between a young jazz drummer and his abusive instructor at a prestigious music academy.",
        glimpse: 'https://youtu.be/7d_jQycdQGo?si=wrSDLPDbwzkmo1QV',
        director: "Damien Chazelle",
        year: 2014,
        cast: ["Miles Teller", "J.K. Simmons"],
        genre: "Drama",
        id: 3
    },
    {
        name: "Babylon",
        poster: "https://upload.wikimedia.org/wikipedia/en/d/db/Babylon_2022_poster.jpg",
        rating: 6.5,
        summary: "Set in 1980s London, 'Babylon' follows a young South London DJ as he navigates the music industry and racial tensions while pursuing his dreams of success.",
        glimpse: 'https://youtu.be/t7HT83wkVss?si=_aFL7uKCAtXZedDY',
        director: "Damien Chazelle",
        year: 1980,
        cast: ["Brinsley Forde", "Karl Howman"],
        genre: "Thriller",
        id: 4
    },
    {
        name: "In Mood for Love",
        poster: "https://upload.wikimedia.org/wikipedia/en/4/45/In_the_Mood_for_Love_movie.jpg",
        rating: 8.1,
        summary: "A visually stunning exploration of love, longing, and missed connections in 1960s Hong Kong, 'In the Mood for Love' is a masterpiece of Wong Kar Wai.",
        glimpse: 'https://youtu.be/m8GuedsQnWQ?si=kVtdzZsW5FFv74-x',
        director: "Wong Kar Wai",
        year: 2000,
        cast: ["Tony Leung", "Maggie Cheung"],
        genre: "Romance",
        id: 5
    },
    // Add Damien Chazelle movie
    {
        name: "La La Land",
        poster: "https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29.png",
        rating: 8.0,
        summary: "A modern musical that captures the bittersweet essence of chasing dreams in Los Angeles, 'La La Land' is a visually stunning and emotionally resonant film by Damien Chazelle.",
        glimpse: 'https://youtu.be/0pdqf4P9MB8?si=JyQfS6lorY-R4cyG',
        director: "Damien Chazelle",
        year: 2016,
        cast: ["Ryan Gosling", "Emma Stone"],
        genre: "Romance",
        id: 6
    },

    {
        name: "Once Upon a Time in Hollywood",
        poster: "https://upload.wikimedia.org/wikipedia/en/a/a6/Once_Upon_a_Time_in_Hollywood_poster.png",
        rating: 7.6,
        summary: "Quentin Tarantino's ode to Hollywood's golden age, 'Once Upon a Time in Hollywood' intertwines the lives of a fading TV star and his stunt double with the Manson Family murders.",
        glimpse: 'https://youtu.be/ELeMaP8EPAA?si=jzqdJiYJgK8Q-OWJ',
        director: "Quentin Tarantino",
        year: 2019,
        cast: ["Leonardo DiCaprio", "Brad Pitt"],
        genre: "Thriller",
        id: 7
    },
    // Add Vikramaditya Motwane movie
    {
        name: "Udaan",
        poster: "https://upload.wikimedia.org/wikipedia/en/7/71/Udaan_Movie_Poster.jpg",
        rating: 8.1,
        summary: "A coming-of-age drama about a teenager's journey of self-discovery and rebellion against his authoritarian father, 'Udaan' is a powerful film by Vikramaditya Motwane.",
        glimpse: 'https://youtu.be/wEJxe2bE-cE?si=9PfMsFlX6XK34dT0',
        director: "Vikramaditya Motwane",
        year: 2010,
        cast: ["Rajat Barmecha", "Ronit Roy"],
        genre: "Drama",
        id: 8
    },
    {
        name: "Masaan",
        poster: "https://upload.wikimedia.org/wikipedia/en/1/1c/Masaan_poster.jpg",
        rating: 8.1,
        summary: "A powerful drama set in the holy city of Varanasi, 'Masaan' explores themes of love, loss, and redemption through the lives of its characters.",
        glimpse: 'https://youtu.be/SKJfBo3xMW0?si=zkgoK5nijp_Ws3Li',
        director: "Neeraj Ghaywan",
        year: 2015,
        cast: ["Richa Chadha", "Vicky Kaushal"],
        genre: "Thriller",
        id: 9
    },
    {
        name: "Jab We Met",
        poster: "https://upload.wikimedia.org/wikipedia/en/9/9f/Jab_We_Met_Poster.jpg",
        rating: 7.9,
        summary: "A romantic comedy about two strangers who meet on a train journey and embark on an adventurous and transformative road trip together.",
        glimpse: 'https://youtu.be/Z6cE7g9feSs?si=91uMA8mRUxdS964f',
        director: "Imtiaz Ali",
        year: 2007,
        cast: ["Shahid Kapoor", "Kareena Kapoor Khan"],
        genre: "Romance",
        id: 10
    },
    {
        name: "Sir",
        poster: "https://upload.wikimedia.org/wikipedia/en/f/fc/Sir_film.jpg",
        rating: 7.2,

        summary: "A tender romance between a wealthy young man and his live-in maid, 'Sir' explores the complexities of class divide and societal norms.",
        glimpse: 'https://youtu.be/h36-Hkno6QQ?si=kBgxbsVypRDYn-ut',
        director: "Rohena Gera",
        year: 2020,
        cast: ["Tillotama Shome", "Vivek Gomber"],
        genre: "Romance",
        id: 11
    },
    {
        name: "Chhichhore",
        poster: "https://upload.wikimedia.org/wikipedia/en/3/3d/Chhichhore_Poster.jpg",
        rating: 7.6,
        summary: "A heartwarming tale about a group of college friends who reunite years later to support one of their own and reminisce about their unforgettable days together.",
        glimpse: 'https://youtu.be/tsxemFX0a7k?si=zZzHqr4h-QTbArX1',
        director: "Nitesh Tiwari",
        year: 2019,
        cast: ["Sushant Singh Rajput", "Shraddha Kapoor"],
        genre: "Drama",
        id: 12
    },

    {
        name: "Tanu Weds Manu 2",
        poster: "https://upload.wikimedia.org/wikipedia/en/3/3f/Tanu_weds_Manu_poster.jpg",
        rating: 7.5,
        summary: "A quirky romantic comedy sequel that follows the tumultuous lives of Tanu and Manu, exploring love, marriage, and second chances.",
        glimpse: 'https://youtu.be/wGGmyaurjAI?si=GWwDBvkWeOHrPO-I',
        director: "Aanand L. Rai",
        year: 2015,
        cast: ["Kangana Ranaut", "R. Madhavan"],
        genre: "Drama",
        id: 13
    },
    {
        name: "Peepli Live",
        poster: "https://upload.wikimedia.org/wikipedia/en/5/55/Peeplilive.jpg",
        rating: 7.5,
        summary: "A satirical comedy-drama that sheds light on the media circus surrounding farmer suicides in rural India and the political exploitation of their plight.",
        glimpse: 'https://youtu.be/ht0-gqvFor0?si=AQic8ACFsZBlXEVs',
        director: "Anusha Rizvi",
        year: 2010,
        cast: ["Omkar Das Manikpuri", "Raghubir Yadav"],
        genre: "Drama",
        id: 14
    },
    {
        name: "Casablanca",
        poster: "https://m.media-amazon.com/images/I/81vQ31ZbomL._AC_UF1000,1000_QL80_.jpg",
        rating: 8.5,
        summary: "A timeless romantic drama set during World War II, showcasing love, sacrifice, and political intrigue in the Moroccan city of Casablanca.",
        glimpse: 'https://youtu.be/MF7JH_54d8c?si=S_utzuo1aKb4qRDL',
        director: "Michael Curtiz",
        year: 1942,
        cast: ["Humphrey Bogart", "Ingrid Bergman"],
        genre: "Thriller",
        id: 15
    },
    {
        name: "Pyaasa",
        poster: "https://upload.wikimedia.org/wikipedia/en/9/93/Pyaasa_poster.jpg",
        rating: 7,
        summary: "Considered a masterpiece of Indian cinema, 'Pyaasa' tells the story of a struggling poet who finds solace and purpose amidst societal indifference and personal turmoil.",
        glimpse: 'https://youtu.be/pBZYJAzz5ys?si=sn_IgsHHw6-h-F3R',
        director: "Guru Dutt",
        year: 1957,
        cast: ["Guru Dutt", "Waheeda Rehman"],
        genre: "Classic",
        id: 16
    },
    {
        name: "Pather Panchali",
        poster: "https://images.squarespace-cdn.com/content/v1/5befb3b84611a081dd003798/1618119957942-CX3XM1T6CCU4KPW0FNRK/Pather+Panchali+%5BA+Song+of+the+Little+Road+1955.jpg",
        rating: 8.6,
        summary: "Regarded as one of the greatest films in world cinema, 'Pather Panchali' is a lyrical portrayal of childhood, poverty, and dreams in rural Bengal, directed by Satyajit Ray.",
        glimpse: 'https://imdb-video.media-imdb.com/vi3114774553/1401497881123-xszl4z-1430514845919.mp4?Expires=1711952609&Signature=lk5dKZIEn2BMShbg5kb9V3uBa6snqpOKdIbyN~JwVrQvXNzXxYs87yMPQkaKhEcbYZEWoA6OuRHrGZkXrnNbHw-~lHmjKXkfhkBFcur68rEmDzs2r03CnSFL-kliwe3jymq8wAmsV51Di~~WUDxO01xdCGi2KJCvKEVQtoKv4K2b1e4AdalI5DLUmzZ1MmKlvE3tYCW-MUmLns6I1DN3yr34dHvmvlsDEXucPMv-juSYIytBMEGdmIWiAiIRiqMG3UiRkHAo60~Y9SprWuiO3YJc4IAgkVdk-7kfvo7f~6cWkEc-HUjx4MqJjhnKvhYjaGDluuPKwNGe3pxT3BPajA__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA',
        director: "Satyajit Ray",
        year: 1955,
        cast: ["Kanu Banerjee", "Karuna Banerjee"],
        genre: "Classic",
        id: 17
    },
    {
        name: "The Seventh Seal",
        poster: "https://upload.wikimedia.org/wikipedia/en/6/69/Seventhsealposter.jpg",
        rating: 6.8,
        summary: "A landmark of Swedish cinema, 'The Seventh Seal' follows a medieval knight's existential crisis as he plays a game of chess with Death, exploring themes of faith",
        glimpse: 'https://www.youtube.com/watch?v=NtkFei4wRjE',
        director: "Ingmar Bergman",
        year: 1957,
        cast: ["Max von Sydow", "Bengt Ekerot"],
        genre: "Classic",
        id: 18
    },
    {
        name: "Persona",
        poster: "https://m.media-amazon.com/images/M/MV5BYmFlOTcxMWUtZTMzMi00NWIyLTkwOTEtNjIxNmViNzc2Yzc1XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg",
        rating: 6.6,
        summary: "Directed by Ingmar Bergman, 'Persona' is an enigmatic psychological drama exploring the blurred boundaries between identity,reality and illusions",
        glimpse: 'https://youtu.be/amxvetvKfho?si=p5f2KcIMJQ3XAGX4',
        director: "Ingmar Bergman",
        year: 1966,
        cast: ["Bibi Andersson", "Liv Ullmann"],
        genre: "Thriller",
        id: 19
    },
    {
        name: "Citizen Kane",
        poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Citizen_Kane_poster%2C_1941_%28Style_B%2C_unrestored%29.jpg/330px-Citizen_Kane_poster%2C_1941_%28Style_B%2C_unrestored%29.jpg",
        rating: 8.3,
        summary: "Regarded as one of the greatest films ever made, 'Citizen Kane' follows the life and legacy of a wealthy newspaper tycoon, exploring themes of power & corruption.",
        glimpse: 'https://youtu.be/8dxh3lwdOFw?si=Yt6AFys8_0Qhe1r-',
        director: "Orson Welles",
        year: 1941,
        cast: ["Orson Welles", "Joseph Cotten"],
        genre: "Classic",
        id: 20
    },
    {
        name: "Gone with Wind",
        poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Poster_-_Gone_With_the_Wind_01.jpg/330px-Poster_-_Gone_With_the_Wind_01.jpg",
        rating: 8.1,
        summary: "A sweeping epic set against the backdrop of the American Civil War and Reconstruction era, 'Gone with the Wind' portrays the tumultuous romance.",
        glimpse: 'https://youtu.be/0X94oZgJis4?si=yi4iNYhx_ySQ0P5e',
        director: "Victor Fleming",
        year: 1939,
        cast: ["Clark Gable", "Vivien Leigh"],
        genre: "Romance",
        id: 21
    },
    {
        name: "Sholay",
        poster: "https://upload.wikimedia.org/wikipedia/en/5/52/Sholay-poster.jpg",
        rating: 8.2,
        summary: "An iconic Bollywood classic, 'Sholay' is a tale of friendship, revenge, and redemption set in the lawless village of Ramgarh, featuring memorable characters.",
        glimpse: 'https://youtu.be/zzTUvWfvlBg?si=ru_MH9bZSCi6Rmmg',
        director: "Ramesh Sippy",
        year: 1975,
        cast: ["Dharmendra", "Amitabh Bachchan"],
        genre: "Classic",
        id: 22
    }
  ,

    {
        name: "La Dolce Vita",
        poster: "https://upload.wikimedia.org/wikipedia/en/c/c1/La_Dolce_Vita_%281960_film%29_coverart.jpg",
        rating: 8.0,
        summary: "Federico Fellini's masterpiece, 'La Dolce Vita', is a satirical take on the hedonistic lifestyles of the Roman elite, capturing the emptiness beneath the glamour of society.",
        glimpse: 'https://youtu.be/1BeWEPXWDX4?si=hOryPsFHIlwyvwR5',
        director: "Federico Fellini",
        year: 1960,
        cast: ["Marcello Mastroianni", "Anita Ekberg"],
        genre: "Classic",
        id: 23
    },
    {
        name: "Mahanagar",
        poster: "https://upload.wikimedia.org/wikipedia/en/1/18/Mahanagar2.jpg",
        rating: 8.2,
        summary: "Directed by Satyajit Ray, 'Mahanagar' (The Big City) explores the evolving role of women in Indian society through the journey of a housewife who takes up a job.",
        glimpse: 'https://youtu.be/HGA8WBTvQco?si=6LLaajAjbCB7SUi8',
        year: 1963,
        cast: ["Madhabi Mukherjee", "Anil Chatterjee"],
        genre: "Drama",
        id: 24
    }
];